# @package _global_

train_ftwc: True
resume_from_checkpoint: null  #/home/guntis/work/0_magd3/tw13/minGPT/saved_models/dec18-startofepoch2.ckpt
val_check_interval: 0.5
limit_val_batches: 50

gpus:   # set to a single int n to auto-select n gpus from all available, or to a list of gpu indices e.g. [0,1,2,3]
  - 0
#  - 2
cwd_path: "."   # gets expanded to an absolute path to the original current directory (not the Hydra/runtime working dir)
use_lightning: True

general:
  use_cuda: True  # disable this when running on machine without cuda
  cuda_idx: 0     # set to None to run without using CUDA
  random_seed: 42

data:
#  vocab_words: ${cwd_path}/vocabulary/vocab.txt
  data_file: ${cwd_path}/mingpt-training-all.pthru
  # data_file: ${cwd_path}/tw-cooking-recipe3+take3+cut+go6-Z7L8CvEPsO53iKDg.pthru  #
  val_file: ${cwd_path}/mingpt-valid-all.pthru
  # val_file: ${cwd_path}/mingpt-training-all.pthru
  test_file: ${cwd_path}/mingpt-test-all.pthru
  tokenizer_file: ${cwd_path}/ftwc_tokenizer.json
  num_workers: 8
  training:
    num_tokens: len(dataset)

gpt:
  block_size: 128  # spatial extent of the model for its context
  n_layer: 8
  n_head: 8
  n_embd: 512
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  vocab_size: 0     # gets filled in after we load the vocabulary

trainer:
  max_epochs: 2
  batch_size: 192
  learning_rate: 6e-4
  lr_decay: true
  betas:
    - 0.9
    - 0.95
  grad_norm_clip: 1.0
  weight_decay: 0.1 # only applied on matmul weights
  warmup_tokens: 10240  #512*20
  # update final_tokeans after loading training data
  final_tokens: 2*${data.training.num_tokens}*${gpt.block_size}
  num_workers: 4

eval:
  # ${cwd_path}/saved_models/mingpt-epoch=60-step=00243-val_loss=0.03.ckpt  #mingpt-epoch=820-step=03281-val_loss=0.02.ckpt
  # ${cwd_path}/saved_models/dec18-startofepoch2.ckpt
  checkpoint: ${cwd_path}/saved_models/dec18-startofepoch2.ckpt
  play_games: False
  pthru_data_dir: /ssd2tb/ftwc/playthru_data/mingpt-valid
  games_dir: /ssd2tb/ftwc/games/valid/

