# @package _global_

train_ftwc: True
resume_from_checkpoint: null  #/home/guntis/work/0_magd3/tw13/minGPT/saved_models/dec18-startofepoch2.ckpt

gpus:   # set to a single int n to auto-select n gpus from all available, or to a list of gpu indices e.g. [0,1,2,3]
  - 0   # this is a list: [0,]
#  - 1
cwd_path: "."   # gets expanded to an absolute path to the original current directory (not the Hydra/runtime working dir)

general:
  random_seed: 42

data:
  data_file: ${cwd_path}/mingpt-training-all.pthru
#  data_file: ${cwd_path}/tw-cooking-recipe3+take3+cut+go6-Z7L8CvEPsO53iKDg.pthru  #
  val_file: ${cwd_path}/mingpt-valid-all.pthru
  test_file:  ${cwd_path}/mingpt-test-all.pthru
  tokenizer_file: ${cwd_path}/ftwc_tokenizer.json
#  data_file: ${cwd_path}/input.txt
#  val_file: ${cwd_path}/input.txt
#  test_file: null
#  tokenizer_file: null
  num_workers: 8
  train_filtering: cmd_tokens
  eval_filtering: cmd_tokens

model:    # Feedback Transformer
  d_embd: 512    # (used to be n_embd) - dimension of input embeddings to transformer blocks
  n_heads: 8
  n_layers: 8
  dropout: 0.1    # embd_pdrop, resid_pdrop, attn_pdrop
  hidden_layer_multiplier: 4          # used directly by xFormers framework
  d_ff:  2048   #${.hidden_layer_multiplier}*${.d_embd}   # 2048 = 4 * d_embd -- FF layer of transformer encoder block
  block_size: 128    # aka block_size or 'attention window size'
  vocab_size:  20000 # number of unique token ids -- set/updated after we load the vocabulary

trainer:
  max_epochs: 6
  batch_size: 192
  learning_rate: 6e-4
  val_check_interval: 1.0
  patience: 25
  save_top_k: 25
  limit_val_batches: 10000  # 10000 should cover all of our current validation set (but maybe not the test set?)
  betas:
    - 0.9
    - 0.95
  grad_norm_clip: 1.0
  lr_decay: true
  weight_decay: 0.1 # only applied on matmul weights
  warmup_tokens: 10240  #512*20
  decay_tokens: 2*${data.training.num_tokens}*${gpt.block_size} # caller updates decay_tokens after loading training data

eval:
  checkpoint: ${cwd_path}/saved_models/dec18-startofepoch2.ckpt

