# @package _global_
# @package _global_

defaults:
# - def_values01  # could optionally provide default config values in external file(s) listed here
  - _self_
  - overrides: null   # can select from config files in conf/overrides/ to override values listed below

cwd_path: "."   # gets expanded to an absolute path to the original current directory (not the Hydra/runtime working dir)

train_ftwc: true
use_wandb: false
use_framework: mingpt   # mingpt, xf (xFormers), hf (huggingface), lml (labml)

resume_from_checkpoint: null  #/home/guntis/work/0_magd3/tw13/minGPT/saved_models/dec18-startofepoch2.ckpt

gpus:  1 # a single int n to auto-select n gpus from those available, or else a list of gpu indices e.g. [0,1,2,3]
#  - 0  # yaml format for a list
#  - 1
#  - 2
#  - 3

general:
  random_seed: 42

data:
  # data_file: ${cwd_path}/tw-cooking-recipe3+take3+cut+go6-Z7L8CvEPsO53iKDg.pthru  #
  data_file: ${cwd_path}/mingpt-training-all.pthru   #gata-train-all.pthru  #
  val_file:  ${cwd_path}/gata-valid-all.pthru  #mingpt-valid-all.pthru
  test_file: ${cwd_path}/gata-test-all.pthru #${cwd_path}/mingpt-test-all.pthru
  tokenizer_file: ${cwd_path}/ftwc_tokenizer.json
  num_workers: 8
  train_filtering: cmd_prompts  # cmd_tokens, cmd_prompts
  eval_filtering: cmd_prompts  #${data.train_filtering}

model:
  arch: gpt
  block_size: 128  # aka seq_len or 'attention window size'
  attention_type: scaled_dot_product  # for xFormers (xf) framework
  n_layers: 7
  n_heads: 8
  d_embd: 512
  hidden_layer_multiplier: 4          # used directly by xFormers framework
  d_ff: 2048  # ${.hidden_layer_multiplier}*${.n_embd}  # FF layer of transformer block
  dropout: 0.1
  embd_pdrop: ${.dropout}
  resid_pdrop: ${.dropout}
  attn_pdrop: ${.dropout}
  mlp_pdrop: ${.dropout}      # used by xFormers framework
  vocab_size: 0     # gets filled in after we load the vocabulary

trainer:
  batch_size: 192
  max_epochs: 3
  learning_rate: 6e-4
  val_check_interval: 1.0  # 0.5
  patience: 25
  save_top_k: 25
  limit_val_batches: 10000  # this should cover all of our current validation set (but maybe not the test set?)
  betas:
    - 0.9
    - 0.95
  grad_norm_clip: 1.0
  lr_decay: true
  weight_decay: 0.1 # only applied on matmul weights
  warmup_tokens: 10240  #512*20
  decay_tokens: 2000*${model.block_size} # 2*${len(dataset)}*${gpt.block_size}  # set by caller after loading training data
  show_samples: true

eval:
#  checkpoint: ${cwd_path}/saved_models/instrgpt-epoch=4-step=1314-train_loss_step=0.125-val_loss=0.231.ckpt
#  checkpoint: ${cwd_path}/saved_models/12-31/mingpt-epoch=1-step=1469-train_loss_step=0.197-val_loss=0.662.ckpt  # 84.2 % (win 27/124)
#  checkpoint: ${cwd_path}/saved_models/2021-01-04_16-24-29/instrgpt-epoch=4-step=1655-train_loss_step=0.129-val_loss=0.258.ckpt  #
  checkpoint: ${cwd_path}/outputs/2021-12-10/11-49-32/lightning_logs/version_0/checkpoints/instrgpt-epoch=5-step=917-train_loss_step=0.228-val_loss=0.239.ckpt
  #instrgpt-epoch=4-step=3380-train_loss_step=0.155-val_loss=0.920.ckpt # 88.29%
  #instrgpt-epoch=4-step=3380-train_loss_step=0.155-val_loss=0.920.ckpt # 88.29%
  # mingpt-epoch=02-step=01616-val_loss=0.66.ckpt  # 83.6 % (win 29/124)
  # mingpt-epoch=2-step=1616-train_loss_step=0.199-val_loss=0.662.ckpt  # 83.6
  play_games: false
  which_set: valid    # valid or test
  which_games: gata   # gata or ftwc
  root_dir: /ssd2tb/${eval.which_games}  # /ssd2tb/ftwc
  pthru_data_dir: ${eval.root_dir}/playthru_data/${eval.which_games}_${eval.which_set}  #mingpt-${eval.which_set}
  games_dir: ${eval.root_dir}/games_${eval.which_games}/${eval.which_set}/

wandb:
  proj: tw-${use_framework}-${model.arch}
  experiment: null

