# @package _global_
# overrides for main config from config.yaml

gpus:  # set to a single int n to auto-select n gpus from all available, or to a list of gpu indices e.g. [0,1,2,3]
  - 0  # yaml format for a list
#  - 1
#  - 2
#  - 3

model:
  block_size: 512  # spatial extent of the model for its context
  d_embd: 512

trainer:
  batch_size: 32
  max_epochs: 6
  learning_rate: 3e-4
  patience: 5
  save_top_k: 5
#  val_check_interval: 0.2
#  limit_val_batches: 10000  # this should cover all of our current validation set (but maybe not the test set?)

eval:
  checkpoint: ${cwd_path}/saved_models/2022-05-18/mingpt:gpt:pthru-epoch=2-step=463-val_acc=0.659-val_loss=0.877.ckpt
  which_set: test   # valid or test
  play_games: true
  which_games: ftwc   # gata or ftwc
#  root_dir: /ssd2tb/twdata/
  pthru_data_dir: /home1/guntis/work/0_magd3/tw13/twagents/playthrus #/home1/guntis/work/0_magd3/tw13/twGPT/tmp
  #/ssd2tb/twdata/ftwc/playthru_data
  #/home1/guntis/work/0_magd3/tw13/twagents/playthrus
#  games_dir: ${.root_dir}/games_${.which_games}/${.which_set}/
  show_samples: false   # ${trainer.eval_predict}
