# @package _global_
# overrides for main config from config.yaml

gpus:  # set to a single int n to auto-select n gpus from all available, or to a list of gpu indices e.g. [0,1,2,3]
#  - 0  # yaml format for a list
#  - 1
  - 2
#  - 3

gpt:
  block_size: 128  # spatial extent of the model for its context
#  n_embd: 256

trainer:
  batch_size: 192
#  max_epochs: 10
#  learning_rate: 6e-4
#  patience: 6
#  save_top_k: 10
#  val_check_interval: 0.2
#  limit_val_batches: 10000  # this should cover all of our current validation set (but maybe not the test set?)

eval:
#  checkpoint: ${cwd_path}/saved_models/12-31/mingpt-epoch=1-step=1469-train_loss_step=0.197-val_loss=0.662.ckpt  # 84.2 % (win 27/124)
  pthru_data_dir: /work2/gstrazds/ftwc/playthru_data/mingpt-valid
  games_dir: /work2/gstrazds/ftwc/games/valid/
