# @package _global_
# overrides for main config from config.yaml

gpus:  # set to a single int n to auto-select n gpus from all available, or to a list of gpu indices e.g. [0,1,2,3]
#  - 0  # yaml format for a list
#  - 1
  - 2
  - 3

model:
#  block_size: 128  # aka seq_len or 'attention window size'
  block_size: 512  # spatial extent of the model for its context
#  n_layers: 7
#  n_heads: 8
  d_embd: 512

trainer:
  batch_size: 32
  max_epochs: 7
  learning_rate: 2e-4
  patience: 30
  save_top_k: 20
#  val_check_interval: 0.2
#  limit_val_batches: 10000  # this should cover all of our current validation set (but maybe not the test set?)

eval:
  root_dir: /work2/gstrazds/ftwc
  checkpoint: ${cwd_path}/saved_models/instrgpt-epoch=3-step=0-train_loss_step=0.018-val_loss=0.646.ckpt  # 90.61% 2021-01-03/10-24-18
  # ${cwd_path}/saved_models/mingpt-epoch=3-step=0-train_loss_step=0.042-val_loss=0.442.ckpt
